import { sql } from "@relay/database";
import { requireApiSession } from "../../../../lib/api-session";
export const runtime="nodejs";
export async function GET(request:Request){const auth=await requireApiSession(request,{apiKeyScope:"posts:read"});if(auth.response)return auth.response;const rows=await sql`SELECT id,brand_id AS "brandId",title,notes,source_url AS "sourceUrl",pillar,status FROM content_idea WHERE owner_id=${auth.session.user.id} ORDER BY updated_at DESC LIMIT 500`;return Response.json({data:rows});}
async function save(request:Request,update:boolean){const auth=await requireApiSession(request,{apiKeyScope:"posts:write"});if(auth.response)return auth.response;try{const b=await request.json();if(typeof b.title!=="string"||!b.title.trim()||b.title.length>200)throw new Error("Title must contain 1–200 characters.");if(update&&typeof b.id!=="string")throw new Error("Idea id required.");const brandId=typeof b.brandId==="string"&&b.brandId?b.brandId:null;if(brandId){const [brand]=await sql`SELECT id FROM brand WHERE id=${brandId} AND owner_id=${auth.session.user.id}`;if(!brand)throw new Error("Brand not found.");}const status=b.status??"idea";if(!["idea","planned","used","archived"].includes(status))throw new Error("Invalid idea status.");const notes=typeof b.notes==="string"?b.notes.slice(0,10000):"";const source=typeof b.sourceUrl==="string"?b.sourceUrl.slice(0,2000):"";if(source&&!/^https?:\/\//.test(source))throw new Error("Source URL must use HTTP or HTTPS.");const pillar=typeof b.pillar==="string"?b.pillar.slice(0,80):"";
 const rows=update?await sql`UPDATE content_idea SET title=${b.title.trim()},notes=${notes},source_url=${source},pillar=${pillar},brand_id=${brandId},status=${status},updated_at=now() WHERE id=${b.id} AND owner_id=${auth.session.user.id} RETURNING id`:await sql`INSERT INTO content_idea(id,owner_id,brand_id,title,notes,source_url,pillar,status) VALUES(${crypto.randomUUID()},${auth.session.user.id},${brandId},${b.title.trim()},${notes},${source},${pillar},${status}) RETURNING id`;
 return rows[0]?Response.json({data:rows[0]},{status:update?200:201}):Response.json({error:"Idea not found."},{status:404});}catch(e){return Response.json({error:(e as Error).message},{status:400});}}
export const POST=(request:Request)=>save(request,false);export const PATCH=(request:Request)=>save(request,true);
export async function DELETE(request:Request){const auth=await requireApiSession(request,{apiKeyScope:"posts:write"});if(auth.response)return auth.response;const b=await request.json().catch(()=>null);if(typeof b?.id!=="string")return Response.json({error:"Idea id required."},{status:400});const rows=await sql`DELETE FROM content_idea WHERE id=${b.id} AND owner_id=${auth.session.user.id} RETURNING id`;return rows[0]?Response.json({data:rows[0]}):Response.json({error:"Idea not found."},{status:404});}
