"use client";

import { AlertTriangle, LoaderCircle, Trash2, X } from "lucide-react";

export function ConfirmModal({ eyebrow = "Please confirm", title, body, confirmLabel = "Confirm", cancelLabel = "Cancel", busy = false, error = "", onClose, onConfirm }: { eyebrow?: string; title: string; body: string; confirmLabel?: string; cancelLabel?: string; busy?: boolean; error?: string; onClose: () => void; onConfirm: () => void }) {
  return <div className="modal-layer"><button className="modal-scrim" disabled={busy} onClick={onClose} aria-label={cancelLabel} /><section className="confirm-modal" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" aria-describedby="confirm-description"><span className="confirm-icon"><AlertTriangle /></span><div><p className="eyebrow">{eyebrow}</p><h2 id="confirm-title">{title}</h2><p id="confirm-description">{body}</p></div><button className="confirm-close icon-button" disabled={busy} onClick={onClose} aria-label="Close"><X /></button>{error && <p className="auth-error" role="alert">{error}</p>}<footer><button className="secondary-button" disabled={busy} onClick={onClose}>{cancelLabel}</button><button className="danger-button" disabled={busy} onClick={onConfirm}>{busy ? <LoaderCircle className="spin" /> : <Trash2 />}{busy ? "Working…" : confirmLabel}</button></footer></section></div>;
}

export function PromptModal({ eyebrow = "Media library", title, body, value, placeholder, confirmLabel, busy = false, error = "", onChange, onClose, onConfirm }: { eyebrow?: string; title: string; body: string; value: string; placeholder?: string; confirmLabel: string; busy?: boolean; error?: string; onChange: (value: string) => void; onClose: () => void; onConfirm: () => void }) {
  return <div className="modal-layer"><button className="modal-scrim" disabled={busy} onClick={onClose} aria-label="Cancel" /><form className="prompt-modal" role="dialog" aria-modal="true" aria-labelledby="prompt-title" onSubmit={(event) => { event.preventDefault(); onConfirm(); }}><header><div><p className="eyebrow">{eyebrow}</p><h2 id="prompt-title">{title}</h2><p>{body}</p></div><button type="button" className="icon-button" disabled={busy} onClick={onClose} aria-label="Close"><X /></button></header><input autoFocus value={value} maxLength={100} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} />{error && <p className="auth-error" role="alert">{error}</p>}<footer><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy || !value.trim()}>{busy ? <LoaderCircle className="spin" /> : null}{busy ? "Saving…" : confirmLabel}</button></footer></form></div>;
}
