"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronLeft, ChevronRight, CircleAlert, Copy, Filter, LoaderCircle, Plus, RefreshCw, Trash2 } from "lucide-react";
import type { Brand, Campaign, ProviderId, RelayPost, SocialAccount } from "@relay/core";

type Mode = "month" | "week" | "list";
const providerNames: Record<ProviderId, string> = { instagram: "Instagram", facebook: "Facebook", tiktok: "TikTok", youtube: "YouTube" };
const dateKey = (date: Date) => `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
const postTime = (post: RelayPost) => post.scheduledAt ?? post.publishedAt ?? post.createdAt;

export default function PlanningCalendar({ posts, brands, accounts, onCompose, onOpen, onDelete, onDuplicate, onRetry, onDeleteMany, onAssignCampaign, onReschedule, onBulkReschedule, demoMode = false, initialCampaigns = [] }: {
  posts: RelayPost[]; brands: Brand[]; accounts: SocialAccount[]; onCompose: (date?: Date) => void; onOpen: (post: RelayPost) => void; onDelete: (post: RelayPost) => void;
  onDuplicate: (posts: RelayPost[]) => Promise<void>; onRetry: (posts: RelayPost[]) => Promise<void>; onDeleteMany: (posts: RelayPost[]) => Promise<void>; onAssignCampaign: (posts: RelayPost[], campaign: Campaign | null) => Promise<boolean>;
  onReschedule: (post: RelayPost, scheduledAt: string) => Promise<boolean>; onBulkReschedule: (updates: Array<{ post: RelayPost; scheduledAt: string }>) => Promise<boolean>; demoMode?: boolean; initialCampaigns?: Campaign[];
}) {
  const [mode, setMode] = useState<Mode>("month"); const [cursor, setCursor] = useState(() => demoMode && posts[0] && postTime(posts[0]) ? new Date(postTime(posts[0])!) : new Date()); const [campaigns, setCampaigns] = useState<Campaign[]>(initialCampaigns);
  const [brandId, setBrandId] = useState("all"); const [accountId, setAccountId] = useState("all"); const [provider, setProvider] = useState<"all" | ProviderId>("all"); const [status, setStatus] = useState("all"); const [campaignId, setCampaignId] = useState("all");
  const [filtersReady, setFiltersReady] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(() => new Set()); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [newCampaign, setNewCampaign] = useState(""); const [bulkCampaignId, setBulkCampaignId] = useState("");
  useEffect(() => { if (demoMode) return; void fetch("/api/v1/campaigns", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { data?: Campaign[] }; if (response.ok) setCampaigns(payload.data ?? []); }); }, [demoMode]);
  useEffect(() => { const query = new URL(window.location.href).searchParams; setBrandId(query.get("brand") || "all"); setAccountId(query.get("account") || "all"); setProvider((query.get("provider") as typeof provider) || "all"); setStatus(query.get("status") || "all"); setCampaignId(query.get("campaign") || "all"); const savedMode = query.get("calendar"); if (savedMode === "month" || savedMode === "week" || savedMode === "list") setMode(savedMode); setFiltersReady(true); }, []);
  useEffect(() => { if (!filtersReady) return; const url = new URL(window.location.href); const set = (key: string, value: string, fallback = "all") => value === fallback ? url.searchParams.delete(key) : url.searchParams.set(key, value); set("brand", brandId); set("account", accountId); set("provider", provider); set("status", status); set("campaign", campaignId); set("calendar", mode, "month"); window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`); }, [brandId, accountId, provider, status, campaignId, mode, filtersReady]);
  const filtered = useMemo(() => posts.filter((post) => postTime(post))
    .filter((post) => brandId === "all" || post.brandId === brandId)
    .filter((post) => accountId === "all" || post.targets.some((target) => target.accountId === accountId))
    .filter((post) => provider === "all" || post.targets.some((target) => target.provider === provider))
    .filter((post) => status === "all" || post.status === status)
    .filter((post) => campaignId === "all" || (campaignId === "none" ? !post.campaignId : post.campaignId === campaignId)), [posts, brandId, accountId, provider, status, campaignId]);
  const chosen = filtered.filter((post) => selected.has(post.id));
  const monthStart = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const calendarStart = new Date(cursor.getFullYear(), cursor.getMonth(), 1 - ((monthStart.getDay() + 6) % 7));
  const monthDates = Array.from({ length: 42 }, (_, index) => new Date(calendarStart.getFullYear(), calendarStart.getMonth(), calendarStart.getDate() + index));
  const weekStart = new Date(cursor); weekStart.setDate(weekStart.getDate() - ((weekStart.getDay() + 6) % 7)); const weekDates = Array.from({ length: 7 }, (_, index) => new Date(weekStart.getFullYear(), weekStart.getMonth(), weekStart.getDate() + index));
  const visibleDates = mode === "week" ? weekDates : monthDates;
  const conflicts = useMemo(() => {
    const conflictIds = new Set<string>(); const scheduled = filtered.filter((post) => post.status === "scheduled" && post.scheduledAt);
    for (let left = 0; left < scheduled.length; left += 1) for (let right = left + 1; right < scheduled.length; right += 1) {
      const first = scheduled[left]; const second = scheduled[right];
      if (Math.abs(new Date(first.scheduledAt!).getTime() - new Date(second.scheduledAt!).getTime()) <= 5 * 60_000 && first.targets.some((target) => second.targets.some((other) => other.accountId === target.accountId))) { conflictIds.add(first.id); conflictIds.add(second.id); }
    }
    return conflictIds;
  }, [filtered]);
  const recommendation = useMemo(() => {
    const measured = posts.filter((post) => post.publishedAt && post.targets.some((target) => (target.analytics?.views ?? 0) > 0)); if (measured.length < 10) return null;
    const scores = new Map<string, { views: number; count: number }>(); for (const post of measured) { const date = new Date(post.publishedAt!); const key = `${date.getDay()}-${date.getHours()}`; const current = scores.get(key) ?? { views: 0, count: 0 }; current.views += post.targets.reduce((sum, target) => sum + (target.analytics?.views ?? 0), 0); current.count += 1; scores.set(key, current); }
    const best = [...scores.entries()].filter(([, value]) => value.count >= 2).sort((a, b) => b[1].views / b[1].count - a[1].views / a[1].count)[0]; if (!best) return null;
    const [day, hour] = best[0].split("-").map(Number); return `${["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"][day]} around ${String(hour).padStart(2, "0")}:00`;
  }, [posts]);
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const rescheduleOnDate = async (post: RelayPost, date: Date) => { if (post.status !== "scheduled" || !post.scheduledAt) return; const previous = new Date(post.scheduledAt); date.setHours(previous.getHours(), previous.getMinutes(), 0, 0); setBusy(post.id); setError(""); const ok = await onReschedule(post, date.toISOString()); if (!ok) setError("The post could not be moved. It may have started publishing."); setBusy(""); };
  const shift = async (days: number) => { const eligible = chosen.filter((post) => (post.status === "draft" || post.status === "scheduled") && postTime(post)); if (!eligible.length) return; setBusy("bulk"); const ok = await onBulkReschedule(eligible.map((post) => ({ post, scheduledAt: new Date(new Date(postTime(post)!).getTime() + days * 86_400_000).toISOString() }))); if (ok) setSelected(new Set()); else setError("The selected posts could not all be rescheduled."); setBusy(""); };
  const createCampaign = async () => {
    if (!newCampaign.trim()) return;
    setBusy("campaign");
    if (demoMode) {
      const now = new Date().toISOString(); const campaign: Campaign = { id: `demo-campaign-${Date.now()}`, brandId: brandId === "all" ? "" : brandId, name: newCampaign.trim(), color: "#7c5cff", status: "active", postCount: 0, createdAt: now, updatedAt: now };
      setCampaigns((current) => [campaign, ...current]); setCampaignId(campaign.id); setNewCampaign(""); setBusy(""); return;
    }
    const response = await fetch("/api/v1/campaigns", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: newCampaign, brandId: brandId === "all" ? "" : brandId }) }); const payload = await response.json() as { data?: Campaign; error?: string }; if (response.ok && payload.data) { setCampaigns((current) => [payload.data!, ...current]); setCampaignId(payload.data.id); setNewCampaign(""); } else setError(payload.error || "Could not create the campaign."); setBusy("");
  };
  const timezone = brandId !== "all" ? brands.find((brand) => brand.id === brandId)?.timezone : null;
  return <div className="page page-enter planning-calendar">
    <header className="planning-head"><div><p className="eyebrow">Campaign planner</p><h2>{mode === "list" ? "All planned content" : mode === "month" ? cursor.toLocaleDateString([], { month: "long", year: "numeric" }) : `${weekDates[0].toLocaleDateString([], { month: "short", day: "numeric" })}–${weekDates[6].toLocaleDateString([], { month: "short", day: "numeric" })}`}</h2><p>{timezone ? `Scheduling in ${timezone}` : "Each post uses its brand timezone; times display in your browser timezone."}</p></div><div className="planning-nav">{mode !== "list" && <><button className="secondary-button" onClick={() => setCursor(new Date())}>Today</button><button className="icon-button" aria-label="Previous period" onClick={() => setCursor((current) => new Date(current.getFullYear(), current.getMonth() + (mode === "month" ? -1 : 0), current.getDate() + (mode === "week" ? -7 : 0)))}><ChevronLeft /></button><button className="icon-button" aria-label="Next period" onClick={() => setCursor((current) => new Date(current.getFullYear(), current.getMonth() + (mode === "month" ? 1 : 0), current.getDate() + (mode === "week" ? 7 : 0)))}><ChevronRight /></button></>}<div className="segmented">{(["month", "week", "list"] as const).map((value) => <button className={mode === value ? "active" : ""} onClick={() => setMode(value)} key={value}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div><button className="primary-button" onClick={() => onCompose()}><Plus /> Create post</button></div></header>
    <section className="planning-filters"><span><Filter /> Filters</span><select aria-label="Brand" value={brandId} onChange={(event) => { setBrandId(event.target.value); setAccountId("all"); }}><option value="all">All brands</option>{brands.map((brand) => <option value={brand.id} key={brand.id}>{brand.name}</option>)}</select><select aria-label="Account" value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="all">All accounts</option>{accounts.filter((account) => brandId === "all" || account.brandId === brandId).map((account) => <option value={account.id} key={account.id}>{account.displayName} · {providerNames[account.provider]}</option>)}</select><select aria-label="Platform" value={provider} onChange={(event) => setProvider(event.target.value as typeof provider)}><option value="all">All platforms</option>{Object.entries(providerNames).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select><select aria-label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{["draft", "scheduled", "publishing", "processing", "published", "failed"].map((value) => <option value={value} key={value}>{value}</option>)}</select><select aria-label="Campaign" value={campaignId} onChange={(event) => setCampaignId(event.target.value)}><option value="all">All campaigns</option><option value="none">No campaign</option>{campaigns.filter((campaign) => campaign.status === "active").map((campaign) => <option value={campaign.id} key={campaign.id}>{campaign.name}</option>)}</select><form onSubmit={(event) => { event.preventDefault(); void createCampaign(); }}><input value={newCampaign} onChange={(event) => setNewCampaign(event.target.value)} placeholder="New campaign" /><button className="secondary-button" disabled={!newCampaign.trim() || busy === "campaign"}>{busy === "campaign" ? <LoaderCircle className="spin" /> : <Plus />} Add</button></form></section>
    {(conflicts.size > 0 || recommendation) && <section className="planning-insights">{conflicts.size > 0 && <span className="warning"><CircleAlert /> {conflicts.size} posts share a destination within five minutes.</span>}{recommendation && <span><Check /> Your strongest measured window is {recommendation}.</span>}</section>}
    {error && <p className="media-error" role="alert"><CircleAlert />{error}<button onClick={() => setError("")}>Dismiss</button></p>}
    {chosen.length > 0 && <section className="bulk-bar"><b>{chosen.length} selected</b><select aria-label="Assign selected posts to campaign" value={bulkCampaignId} onChange={(event) => setBulkCampaignId(event.target.value)}><option value="">No campaign</option>{campaigns.filter((campaign) => campaign.status === "active" && (!campaign.brandId || chosen.every((post) => post.brandId === campaign.brandId))).map((campaign) => <option value={campaign.id} key={campaign.id}>{campaign.name}</option>)}</select><button onClick={() => void onAssignCampaign(chosen, campaigns.find((campaign) => campaign.id === bulkCampaignId) ?? null).then((ok) => { if (ok) setSelected(new Set()); })}>Assign</button><button onClick={() => void shift(1)}><CalendarDays /> +1 day</button><button onClick={() => void shift(7)}><CalendarDays /> +1 week</button><button onClick={() => void onDuplicate(chosen)}><Copy /> Duplicate</button>{chosen.some((post) => post.status === "failed") && <button onClick={() => void onRetry(chosen.filter((post) => post.status === "failed"))}><RefreshCw /> Retry failed</button>}<button className="danger" onClick={() => void onDeleteMany(chosen)}><Trash2 /> Cancel/delete</button><button onClick={() => setSelected(new Set())}>Clear</button></section>}
    {mode === "list" ? <div className="planning-list">{filtered.map((post) => <PlanningEvent post={post} selected={selected.has(post.id)} conflict={conflicts.has(post.id)} busy={busy === post.id} onSelect={() => toggle(post.id)} onOpen={() => onOpen(post)} onDelete={() => onDelete(post)} key={post.id} />)}</div> : <div className={`planning-grid ${mode}`}><div className="planning-weekdays">{visibleDates.slice(0, 7).map((date) => <b key={date.toISOString()}>{date.toLocaleDateString([], { weekday: "short" })}</b>)}</div><div className="planning-days">{visibleDates.map((date) => <section className={`${date.getMonth() !== cursor.getMonth() && mode === "month" ? "outside" : ""} ${dateKey(date) === dateKey(new Date()) ? "today" : ""}`} title={`Create a post on ${date.toLocaleDateString()}`} onClick={(event) => { if (!(event.target as HTMLElement).closest(".planning-event")) onCompose(new Date(date)); }} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const post = posts.find((item) => item.id === event.dataTransfer.getData("text/relay-post")); if (post) void rescheduleOnDate(post, new Date(date)); }} key={date.toISOString()}><header><b>{date.getDate()}</b><span>{date.toLocaleDateString([], { month: "short" })}</span></header>{filtered.filter((post) => postTime(post) && dateKey(new Date(postTime(post)!)) === dateKey(date)).map((post) => <PlanningEvent post={post} selected={selected.has(post.id)} conflict={conflicts.has(post.id)} busy={busy === post.id} onSelect={() => toggle(post.id)} onOpen={() => onOpen(post)} onDelete={() => onDelete(post)} key={post.id} />)}</section>)}</div></div>}
  </div>;
}

function PlanningEvent({ post, selected, conflict, busy, onSelect, onOpen, onDelete }: { post: RelayPost; selected: boolean; conflict: boolean; busy: boolean; onSelect: () => void; onOpen: () => void; onDelete: () => void }) {
  const deletable = post.status !== "publishing" && post.status !== "processing";
  return <article className={`planning-event ${post.status} ${selected ? "selected" : ""} ${conflict ? "conflict" : ""}`} draggable={post.status === "scheduled"} onDragStart={(event) => { event.dataTransfer.setData("text/relay-post", post.id); event.dataTransfer.effectAllowed = "move"; }}><button className="planning-check" aria-label={selected ? "Deselect post" : "Select post"} onClick={(event) => { event.stopPropagation(); onSelect(); }}>{selected ? <Check /> : null}</button><button className="planning-event-main" onClick={onOpen}><span>{post.scheduledAt ? new Date(post.scheduledAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : post.status}</span><b>{post.text || "Media post"}</b><small>{post.campaignName ?? post.targets.map((target) => providerNames[target.provider]).join(", ")}</small></button><span className="planning-event-actions">{conflict && <CircleAlert />}{busy && <LoaderCircle className="spin" />}{deletable && <button className="planning-event-delete" aria-label={`Delete ${post.status} post`} title={post.status === "scheduled" ? "Cancel scheduled post" : "Delete post"} onClick={(event) => { event.stopPropagation(); onDelete(); }}><Trash2 /></button>}</span></article>;
}
