"use client";
import type { CreativeLabel, SocialAccount, VideoProject } from "@relay/core";
import { Film, LoaderCircle, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import VideoLabelEditor from "./video-label-editor";
import { ConfirmModal } from "./confirm-modal";
interface VideoComposerSeed { media: { name: string; url: string; previewUrl: string; type: "video" }; text: string; brandId: string }
const starterLabel = (): CreativeLabel => ({ id: crypto.randomUUID(), text: "Your hook goes here", x: .5, y: .18, width: .84, height: .12, fontSize: 72, font: "modern", textColor: "#FFFFFF", background: "dark", backgroundColor: "#000000", style: "dark" });

export default function VideoStudio({ accounts, onCompose, demoMode = false, initialProjects = [] }: { accounts: SocialAccount[]; onCompose: (seed: VideoComposerSeed) => void; demoMode?: boolean; initialProjects?: VideoProject[] }) {
  const [projects, setProjects] = useState<VideoProject[]>(initialProjects); const [active, setActive] = useState<VideoProject | null>(null); const [loading, setLoading] = useState(!demoMode); const [error, setError] = useState(""); const [creating, setCreating] = useState(false); const [pendingDelete, setPendingDelete] = useState<VideoProject | null>(null);
  useEffect(() => { void fetch("/api/v1/videos", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { data?: VideoProject[]; error?: string }; if (!response.ok) throw new Error(payload.error || "Could not load videos."); if (!demoMode || (payload.data?.length ?? 0) > 0) setProjects(payload.data ?? []); }).catch((reason) => { if (!demoMode) setError(reason instanceof Error ? reason.message : "Could not load videos."); }).finally(() => setLoading(false)); }, [demoMode]);
  const keep = (project: VideoProject) => setProjects((current) => [project, ...current.filter((item) => item.id !== project.id)]);
  const create = async () => { setCreating(true); const response = await fetch("/api/v1/videos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Untitled video", caption: "", sourceUrl: "", labels: [starterLabel()] }) }); const payload = await response.json() as { data?: VideoProject; error?: string }; if (response.ok && payload.data) { keep(payload.data); setActive(payload.data); } else setError(payload.error || "Could not create a video project."); setCreating(false); };
  const remove = async () => { if (!pendingDelete) return; const response = await fetch("/api/v1/videos", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: pendingDelete.id }) }); if (response.ok) { setProjects((current) => current.filter((item) => item.id !== pendingDelete.id)); setPendingDelete(null); } else setError("Could not delete the project."); };
  if (active) return <VideoLabelEditor initial={active} accounts={accounts} onBack={() => setActive(null)} onSaved={keep} onCompose={onCompose} />;
  return <div className="page video-library page-enter"><div className="inline-heading"><div><p className="eyebrow">Reusable creative</p><h2>Video studio</h2><p>Combine clips, build your story, and turn templates into scheduled content.</p></div><button className="primary-button" disabled={creating} onClick={() => void create()}>{creating ? <LoaderCircle className="spin"/> : <Plus/>} New video recipe</button></div>{error && <p className="composer-error">{error}</p>}{loading ? <div className="media-loading"><LoaderCircle className="spin"/>Loading video recipes…</div> : projects.length ? <div className="video-project-grid">{projects.map((project) => <article key={project.id}><button onClick={() => setActive(project)}>{project.renderedUrl || project.sourceUrl ? <video src={project.renderedUrl || project.sourceUrl} muted preload="metadata"/> : <span><Film/></span>}<em>{project.labels.length} label{project.labels.length === 1 ? "" : "s"}</em></button><div><button onClick={() => setActive(project)}><b>{project.name}</b><span>{project.musicUrl ? "Music ready" : "Original audio"} · edited {new Date(project.updatedAt).toLocaleDateString()}</span></button><button className="icon-button danger" onClick={() => setPendingDelete(project)}><Trash2/></button></div></article>)}</div> : <div className="empty slideshow-empty"><span><Film/></span><h3>No video recipes yet</h3><p>Choose a clip from an R2 folder, drag a label into position, select music, then render one or create a whole hook batch.</p><button className="primary-button" onClick={() => void create()}><Plus/> Create video recipe</button></div>}{pendingDelete && <ConfirmModal eyebrow="Delete video recipe" title={`Delete “${pendingDelete.name}”?`} body="Rendered videos already stored in R2 and scheduled posts will stay available." confirmLabel="Delete recipe" busy={false} error="" onClose={() => setPendingDelete(null)} onConfirm={() => void remove()}/>}</div>;
}
