import { readFileSync } from "node:fs";
import { expect,test } from "@playwright/test";
test("timeline edits autosave, render asynchronously and hand off to composer",async({page})=>{
 let project:any={id:"timeline-test",brandId:"brand-aster",name:"Three clip story",caption:"A useful story",sourceUrl:"",labels:[],revision:1,createdAt:"2026-09-01T00:00:00Z",updatedAt:"2026-09-01T00:00:00Z",timeline:{version:1,aspectRatio:"9:16",clips:[0,1,2].map(i=>({id:`clip-${i}`,sourceUrl:`https://media.example.test/${i}.png`,name:`Scene ${i+1}`,kind:"image",inMs:0,outMs:5000,fit:"cover",x:.5,y:.5,zoom:1,volume:1})),labels:[],music:{url:"",volume:.8,offsetMs:0,fadeInMs:0,fadeOutMs:0},coverMs:0}};
 let saved:any=null;let renderRequest:any=null;
 await page.route("https://media.example.test/**",route=>route.fulfill({contentType:"image/svg+xml",body:'<svg xmlns="http://www.w3.org/2000/svg" width="320" height="480"><rect width="320" height="480" fill="#376456"/></svg>'}));
 await page.route("**/api/v1/videos",async route=>{if(route.request().method()==="PATCH"){saved=route.request().postDataJSON();project={...saved,revision:project.revision+1};return route.fulfill({json:{data:project}});}return route.fulfill({json:{data:[project]}});});
 await page.route("**/api/v1/videos/jobs*",route=>route.fulfill({json:{data:route.request().url().includes("?id=")?{id:"render-1",projectId:project.id,revision:project.revision,status:"completed",progress:100,renderedUrl:"https://media.example.test/output.mp4",coverUrl:"https://media.example.test/cover.jpg",coverMs:0}:[]}}));
 await page.route("**/api/v1/videos/render",route=>{renderRequest=route.request().postDataJSON();return route.fulfill({status:202,json:{job:{id:"render-1",projectId:project.id,revision:project.revision,status:"queued",progress:0}}});});
 for(const path of ["media/projects","brands/kit"])await page.route(`**/api/v1/${path}`,route=>route.fulfill({json:{data:[]}}));
 await page.route("**/api/v1/media?**",route=>route.fulfill({json:{data:route.request().url().includes("kind=music")?[{key:"music/voice.wav",name:"Voice track.wav",url:"https://media.example.test/voice.wav"}]:[{key:"media/photo.png",name:"Photo.png",url:"https://media.example.test/photo.png"}]}}));
 await page.route("**/api/v1/videos/download?**",route=>route.fulfill({contentType:"video/mp4",headers:{"Content-Disposition":'attachment; filename="story.mp4"'},body:Buffer.from("test video")}));
 await page.goto("/demo?view=videos");await page.getByRole("button",{name:"Three clip story"}).click();
 await expect(page.locator(".video-studio-head").getByText("Video studio",{exact:true})).toBeVisible();await expect(page.getByText("Canvas background",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Add text label",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:/Open timeline editor|Label recipes/})).toHaveCount(0);await expect(page.locator(".timeline-clips>button")).toHaveCount(3);await page.getByLabel("Aspect ratio").selectOption("1:1");
 await page.locator(".timeline-clips>button").first().click();await page.getByLabel("Trim end (ms)").fill("3000");
 await page.getByRole("button",{name:"Duplicate",exact:true}).click();await expect(page.locator(".timeline-clips>button")).toHaveCount(4);
 await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(page.locator(".timeline-clips>button")).toHaveCount(3);
 await expect(page.getByRole("button",{name:"Templates",exact:true})).toHaveCount(0);
 await page.getByRole("button",{name:"Add media",exact:true}).click();
 await page.getByRole("button",{name:"Add Photo.png",exact:true}).click();await expect(page.locator(".timeline-clips>button")).toHaveCount(4);
 await page.getByRole("button",{name:"Add audio",exact:true}).last().click();
 await expect(page.getByRole("dialog",{name:"Video assets"})).toBeVisible();
 await page.getByRole("button",{name:"Use audio",exact:true}).click();
 await expect(page.getByLabel("Audio timeline controls")).toBeVisible();
 await page.getByLabel("Audio starts at (s)").fill("2");await page.getByLabel("Audio ends at (s)").fill("10");
 await page.getByLabel("Trim audio from (s)").fill("1.5");await page.getByLabel("Fade in (s)").fill("0.5");
 await expect.poll(()=>saved?.timeline.music.startMs).toBe(2000);await expect.poll(()=>saved?.timeline.music.endMs).toBe(10000);await expect.poll(()=>saved?.timeline.music.offsetMs).toBe(1500);
 await page.getByRole("button",{name:"Edit audio: Voice track.wav"}).focus();await page.keyboard.press("ArrowRight");
 await expect.poll(()=>saved?.timeline.music.startMs).toBe(2100);
 await expect.poll(()=>saved?.timeline.music.endMs).toBe(10100);
 const audioLane=page.locator(".video-audio-lane");await audioLane.scrollIntoViewIfNeeded();
 const laneBounds=(await audioLane.boundingBox())!;const startEdge=(await page.locator('.video-audio-edge[data-edge="start"]').boundingBox())!;
 await page.mouse.move(startEdge.x+startEdge.width/2,startEdge.y+startEdge.height/2);await page.mouse.down();await page.mouse.move(startEdge.x+startEdge.width/2+laneBounds.width/18,startEdge.y+startEdge.height/2,{steps:5});await page.mouse.up();
 await expect.poll(()=>saved?.timeline.music.startMs).toBe(3100);await expect.poll(()=>saved?.timeline.music.offsetMs).toBe(2500);await expect.poll(()=>saved?.timeline.music.endMs).toBe(10100);
 for(let i=0;i<3;i++){await page.locator(".timeline-clips>button").last().click();await page.getByRole("button",{name:"Delete",exact:true}).click();}
 await page.getByRole("button",{name:"Audio outside video · Move to start",exact:true}).click();
 await expect.poll(()=>saved?.timeline.music.startMs).toBe(0);await expect.poll(()=>saved?.timeline.music.endMs).toBe(3000);
 for(let i=0;i<4;i++)await page.getByRole("button",{name:"Undo",exact:true}).click();
 await expect(page.locator(".timeline-clips>button")).toHaveCount(4);
 await page.route("**/api/v1/media",route=>{expect(route.request().postDataJSON().kind).toBe("music");return route.fulfill({json:{key:"music/narration.wav",url:"https://media.example.test/narration.wav",uploadUrl:"https://media.example.test/upload"}});});
 await page.getByRole("button",{name:"Replace audio",exact:true}).click();
 await page.locator('input[type="file"][accept="audio/*"]').setInputFiles({name:"Narration.wav",mimeType:"audio/wav",buffer:Buffer.from("test audio")});
 await expect(page.getByRole("button",{name:"Edit audio: Narration.wav"})).toBeVisible();
 await expect.poll(()=>saved?.timeline.music.name).toBe("Narration.wav");
 await page.getByRole("button",{name:"Remove audio",exact:true}).click();await expect(page.locator(".video-audio-block")).toHaveCount(0);
 await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(page.getByRole("button",{name:"Edit audio: Narration.wav"})).toBeVisible();
 await expect.poll(()=>saved?.timeline.aspectRatio).toBe("1:1");await expect.poll(()=>saved?.timeline.clips[0].outMs).toBe(3000);
 const download=page.waitForEvent("download");await page.getByRole("button",{name:"Save & download",exact:true}).click();await expect.poll(()=>renderRequest?.async).toBe(true);await expect(page.getByRole("button",{name:/Create post from revision/})).toBeVisible();await expect(page.getByRole("link",{name:"Download MP4"})).toBeVisible();const exported=await download;expect(exported.suggestedFilename()).toBe("story.mp4");expect(readFileSync((await exported.path())!).toString()).toBe("test video");await expect(page.getByRole("dialog",{name:"Create post"})).toHaveCount(0);
 await page.screenshot({path:`/tmp/relay-timeline-${test.info().project.name}.png`,fullPage:true});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await page.getByRole("button",{name:/Create post from revision/}).click();await expect(page.getByRole("dialog",{name:"Create post"})).toBeVisible();
});
