import { sql } from "@relay/database";
import { requireApiSession } from "../../../../../lib/api-session";
export const runtime="nodejs";
export async function GET(request:Request){const auth=await requireApiSession(request,{apiKeyScope:"analytics:read"});if(auth.response)return auth.response;const accountId=new URL(request.url).searchParams.get("accountId");if(!accountId)return Response.json({error:"accountId required."},{status:400});
 const [account]=await sql<{timezone:string}[]>`SELECT COALESCE(q.timezone,b.timezone,'UTC') AS timezone FROM social_account a LEFT JOIN publishing_queue q ON q.account_id=a.id LEFT JOIN brand b ON b.id=a.brand_id WHERE a.id=${accountId} AND a.owner_id=${auth.session.user.id}`;if(!account)return Response.json({error:"Account not found."},{status:404});
 const rows=await sql<{hour:number;day:number;media_type:string;views:number}[]>`SELECT EXTRACT(hour FROM p.published_at AT TIME ZONE ${account.timezone})::int AS hour,EXTRACT(dow FROM p.published_at AT TIME ZONE ${account.timezone})::int AS day,p.media_type,m.views::float8 FROM post p JOIN post_target t ON t.post_id=p.id JOIN LATERAL (SELECT views FROM post_metric_snapshot WHERE target_id=t.id AND views IS NOT NULL AND captured_at BETWEEN p.published_at+interval '58 hours' AND p.published_at+interval '72 hours' ORDER BY captured_at DESC LIMIT 1) m ON true WHERE p.owner_id=${auth.session.user.id} AND t.social_account_id=${accountId} AND p.published_at BETWEEN now()-interval '180 days' AND now()-interval '72 hours'`;
 const groups=new Map<string,{day:number;hour:number;mediaType:string;views:number[]}>();for(const r of rows){const key=`${r.day}-${r.hour}-${r.media_type}`;const g=groups.get(key)??{day:r.day,hour:r.hour,mediaType:r.media_type,views:[]};g.views.push(r.views);groups.set(key,g);}
 return Response.json({data:{timezone:account.timezone,totalPosts:rows.length,minimumPosts:20,note:"Observed 58–72 hour views, grouped by this account's content type and local weekday/hour. Associations do not establish a causal best time.",recommendations:rows.length<20?[]:[...groups.values()].filter(g=>g.views.length>=3).map(g=>{const sorted=[...g.views].sort((a,b)=>a-b);return{day:g.day,hour:g.hour,mediaType:g.mediaType,sample:g.views.length,medianViews:sorted[Math.floor(sorted.length/2)]};}).sort((a,b)=>b.medianViews-a.medianViews).slice(0,5)}});
}
