import { sql } from "@relay/database";
import { normalizePublishingDefaults } from "@relay/core";
import { requireApiSession } from "../../../../../lib/api-session";
import { campaignRecipes,validateRecipeEntries,type CampaignRecipeEntry } from "../../../../../lib/campaign-recipes";
import { POST as createPosts } from "../../posts/route";
export const runtime="nodejs";
export async function GET(request:Request){const auth=await requireApiSession(request,{apiKeyScope:"posts:read"});if(auth.response)return auth.response;return Response.json({data:[...campaignRecipes,...await sql`SELECT id,name,entries FROM campaign_recipe WHERE owner_id=${auth.session.user.id} ORDER BY created_at DESC LIMIT 200`]});}
export async function POST(request:Request){const auth=await requireApiSession(request,{apiKeyScope:"posts:write"});if(auth.response)return auth.response;
try{const b=await request.json();if(b.action!=="apply"){if(typeof b.name!=="string"||!b.name.trim()||b.name.length>120)throw new Error("Recipe name required.");const entries=validateRecipeEntries(b.entries);const [row]=await sql`INSERT INTO campaign_recipe(id,owner_id,name,entries) VALUES(${crypto.randomUUID()},${auth.session.user.id},${b.name.trim()},${JSON.stringify(entries)}::jsonb) RETURNING id,name,entries`;return Response.json({data:row},{status:201});}
 if(typeof b.recipeId!=="string"||typeof b.clientRequestId!=="string"||!b.clientRequestId||b.clientRequestId.length>190||!Array.isArray(b.accountIds)||!b.accountIds.length||b.accountIds.length>12||b.accountIds.some((v:unknown)=>typeof v!=="string"))throw new Error("Apply needs recipeId, stable clientRequestId and 1–12 accountIds.");
 const recipe: {name:string;entries:CampaignRecipeEntry[]}|undefined=campaignRecipes.find(r=>r.id===b.recipeId)??(await sql<{name:string;entries:CampaignRecipeEntry[]}[]>`SELECT name,entries FROM campaign_recipe WHERE id=${b.recipeId} AND owner_id=${auth.session.user.id}`)[0];if(!recipe)throw new Error("Recipe not found.");
 const accounts=await sql<{id:string;provider:string}[]>`SELECT id,provider FROM social_account WHERE id=ANY(${b.accountIds}) AND owner_id=${auth.session.user.id}`;if(accounts.length!==new Set(b.accountIds).size)throw new Error("Account not found.");
 const start=typeof b.startAt==="string"?new Date(b.startAt):new Date(Date.now()+86400000);if(!Number.isFinite(start.getTime())||start.getTime()<=Date.now())throw new Error("Choose a future startAt.");
 const [prefs]=await sql<{publishing_defaults:unknown}[]>`SELECT publishing_defaults FROM "user" WHERE id=${auth.session.user.id}`;const defaults=normalizePublishingDefaults(prefs?.publishing_defaults);
 const [campaign]=await sql<{id:string}[]>`INSERT INTO campaign(id,owner_id,name,color,client_request_id) VALUES(${crypto.randomUUID()},${auth.session.user.id},${recipe.name},'#64855c',${b.clientRequestId}) ON CONFLICT(owner_id,client_request_id) WHERE client_request_id IS NOT NULL DO UPDATE SET updated_at=campaign.updated_at RETURNING id`;
 const data=[];
 for(let i=0;i<recipe.entries.length;i++){const entry=recipe.entries[i];const targets=accounts.map(a=>({accountId:a.id,settings:a.provider==="instagram"?{kind:"instagram",publishType:"feed"}:a.provider==="facebook"?{kind:"facebook",publishType:"feed"}:a.provider==="youtube"?{kind:"youtube",title:entry.title,tags:[],...defaults.youtube}:{kind:"tiktok",...defaults.tiktok}}));const response=await createPosts(new Request(new URL("/api/v1/posts",request.url),{method:"POST",headers:request.headers,body:JSON.stringify({clientRequestId:`${b.clientRequestId}-${i}`,campaignId:campaign.id,text:entry.text,mediaType:"none",status:"draft",targets})}));const payload=await response.json();if(!response.ok){data.push({index:i,error:payload.error});continue;}const plannedAt=new Date(start.getTime()+entry.dayOffset*86400000).toISOString();await sql`UPDATE post SET scheduled_at=COALESCE(scheduled_at,${plannedAt}::timestamptz) WHERE id=${payload.data.id} AND owner_id=${auth.session.user.id} AND status='draft'`;data.push({index:i,postId:payload.data.id,plannedAt,format:entry.format,status:"draft",needsMedia:entry.format!=="text"});}
 return Response.json({data:{campaignId:campaign.id,posts:data,note:"Draft briefs only. Add the requested media and review each destination before scheduling. Day offsets preserve elapsed 24-hour periods."}},{status:data.some(p=>p.error)?207:201});
}catch(e){return Response.json({error:(e as Error).message},{status:400});}}
export async function DELETE(request:Request){const auth=await requireApiSession(request,{apiKeyScope:"posts:write"});if(auth.response)return auth.response;const b=await request.json().catch(()=>null);if(typeof b?.id!=="string")return Response.json({error:"Recipe id required."},{status:400});const rows=await sql`DELETE FROM campaign_recipe WHERE id=${b.id} AND owner_id=${auth.session.user.id} RETURNING id`;return rows[0]?Response.json({data:rows[0]}):Response.json({error:"Recipe not found."},{status:404});}
